In [3]:
# ex. 1
import numpy as np

In [5]:
# ex. 2
zecezerouri=np.zeros(10)
zecezerouri

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
# ex.3
vector = np.linspace(10,100,90) 
vector

array([ 10.        ,  11.01123596,  12.02247191,  13.03370787,
        14.04494382,  15.05617978,  16.06741573,  17.07865169,
        18.08988764,  19.1011236 ,  20.11235955,  21.12359551,
        22.13483146,  23.14606742,  24.15730337,  25.16853933,
        26.17977528,  27.19101124,  28.20224719,  29.21348315,
        30.2247191 ,  31.23595506,  32.24719101,  33.25842697,
        34.26966292,  35.28089888,  36.29213483,  37.30337079,
        38.31460674,  39.3258427 ,  40.33707865,  41.34831461,
        42.35955056,  43.37078652,  44.38202247,  45.39325843,
        46.40449438,  47.41573034,  48.42696629,  49.43820225,
        50.4494382 ,  51.46067416,  52.47191011,  53.48314607,
        54.49438202,  55.50561798,  56.51685393,  57.52808989,
        58.53932584,  59.5505618 ,  60.56179775,  61.57303371,
        62.58426966,  63.59550562,  64.60674157,  65.61797753,
        66.62921348,  67.64044944,  68.65168539,  69.66292135,
        70.6741573 ,  71.68539326,  72.69662921,  73.70

In [17]:
# ex. 4
vectorreshaped= np.flip(vector)
vectorreshaped

array([100.        ,  98.98876404,  97.97752809,  96.96629213,
        95.95505618,  94.94382022,  93.93258427,  92.92134831,
        91.91011236,  90.8988764 ,  89.88764045,  88.87640449,
        87.86516854,  86.85393258,  85.84269663,  84.83146067,
        83.82022472,  82.80898876,  81.79775281,  80.78651685,
        79.7752809 ,  78.76404494,  77.75280899,  76.74157303,
        75.73033708,  74.71910112,  73.70786517,  72.69662921,
        71.68539326,  70.6741573 ,  69.66292135,  68.65168539,
        67.64044944,  66.62921348,  65.61797753,  64.60674157,
        63.59550562,  62.58426966,  61.57303371,  60.56179775,
        59.5505618 ,  58.53932584,  57.52808989,  56.51685393,
        55.50561798,  54.49438202,  53.48314607,  52.47191011,
        51.46067416,  50.4494382 ,  49.43820225,  48.42696629,
        47.41573034,  46.40449438,  45.39325843,  44.38202247,
        43.37078652,  42.35955056,  41.34831461,  40.33707865,
        39.3258427 ,  38.31460674,  37.30337079,  36.29

In [19]:
# ex. 5, reshape it to a 3x30
reshaped3x30=vector.reshape(3, 30)
reshaped3x30

array([[ 10.        ,  11.01123596,  12.02247191,  13.03370787,
         14.04494382,  15.05617978,  16.06741573,  17.07865169,
         18.08988764,  19.1011236 ,  20.11235955,  21.12359551,
         22.13483146,  23.14606742,  24.15730337,  25.16853933,
         26.17977528,  27.19101124,  28.20224719,  29.21348315,
         30.2247191 ,  31.23595506,  32.24719101,  33.25842697,
         34.26966292,  35.28089888,  36.29213483,  37.30337079,
         38.31460674,  39.3258427 ],
       [ 40.33707865,  41.34831461,  42.35955056,  43.37078652,
         44.38202247,  45.39325843,  46.40449438,  47.41573034,
         48.42696629,  49.43820225,  50.4494382 ,  51.46067416,
         52.47191011,  53.48314607,  54.49438202,  55.50561798,
         56.51685393,  57.52808989,  58.53932584,  59.5505618 ,
         60.56179775,  61.57303371,  62.58426966,  63.59550562,
         64.60674157,  65.61797753,  66.62921348,  67.64044944,
         68.65168539,  69.66292135],
       [ 70.6741573 ,  71.6853

In [38]:
# ex. 6, Create the vector with elems 1,2,9,0,0,1,4,0. Find indices of non-zero elems.
nou=np.array(([1,2,9,0,0,1,4,0]))


for i in np.arange(len(nou)):
    if nou[i]!=0: 
        print(i)


0
1
2
5
6


In [40]:
# ex. 7, create a 3x3 identity matrix
I3=np.identity(3)
I3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
# ex. 8,create a random vector of size 50 with values uniformely distributed in (-1, 1).
A=np.random.uniform(-1, 1,50)
print(A)
print(A.mean())

[-0.35555726  0.79798637  0.92488444 -0.02799193 -0.61466821  0.2810767
 -0.85313345 -0.40784442 -0.02067095 -0.12785132 -0.51023232  0.7434552
  0.84950959 -0.62077198  0.8711694   0.77159045 -0.79290121  0.44941406
  0.59755954  0.82907749 -0.01968761  0.78655007 -0.9044606  -0.08837142
  0.00835591 -0.16618628  0.66039815 -0.23374629 -0.12877364  0.5913276
 -0.03699595 -0.28941388 -0.77872639  0.65675916 -0.35662117 -0.3216991
  0.64027117  0.17814018 -0.24610579  0.82543054 -0.20609733 -0.19976073
 -0.44600278  0.16347653  0.15803533  0.49995342 -0.0027355   0.3073845
  0.79417737 -0.39522199]
0.08467507316123428


In [80]:
# ex. 9, create a 5x5 matrix with 1,2,3,4 just below the 1st diag and 0 in rest.
X=np.identity(5)
A=X.shape

np.arange(len(X))
for i in np.arange(A[0]):
    for j in np.arange(A[1]):
        if i==j: X[(i,j)]=0
        if i-1==j: X[(i,j)]=i
print(X), 


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


(None,)

In [87]:
# ex. 10, Create a 5x3 matrix and a 3x4 one. Multiply them.
A=np.random.rand(5,3)
B=np.random.rand(3,4)
print(A)
print(B)
H=np.dot(A,B)

[[0.89793431 0.43837832 0.04048228]
 [0.53750809 0.63616013 0.21665088]
 [0.90911378 0.72108992 0.66411305]
 [0.8570214  0.93366182 0.96681249]
 [0.2654056  0.45690751 0.91860424]]
[[0.56705848 0.09399204 0.41828344 0.42049967]
 [0.21362106 0.92339508 0.53739031 0.9143889 ]
 [0.95795405 0.46999728 0.26631142 0.4707391 ]]


In [88]:
#ex. 11, Using the previous matrix, extract a new one with just the integer part of the values. 
#Find at least 4 methods of doing this.
print(np.floor(H))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 0. 1.]
 [1. 1. 1. 1.]
 [1. 0. 0. 0.]]


In [92]:
# ex. 12, Create a random vector of size 25. Sort it.
randomvector=np.random.rand(25)
print(randomvector), print(np.sort(randomvector))

[0.728844   0.02502852 0.80472085 0.44511728 0.18102893 0.52750629
 0.03857472 0.36597654 0.82207638 0.03087014 0.40753748 0.87016625
 0.0435506  0.95433837 0.36728751 0.43843242 0.23040196 0.1270726
 0.87474012 0.70515114 0.13402837 0.25028987 0.32598796 0.84077156
 0.75478717]
[0.02502852 0.03087014 0.03857472 0.0435506  0.1270726  0.13402837
 0.18102893 0.23040196 0.25028987 0.32598796 0.36597654 0.36728751
 0.40753748 0.43843242 0.44511728 0.52750629 0.70515114 0.728844
 0.75478717 0.80472085 0.82207638 0.84077156 0.87016625 0.87474012
 0.95433837]


(None, None)

In [118]:
# ex. 13, Create a random 7x2 matrix representing 7 2D points. Convert them to polar coordinates.
puncte=np.random.random((7,2))

x,y = puncte[:,0], puncte[:,1]

r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)
P=np.dstack((r,t))

P.reshape(7,2)
#V=np.dstack((r,t)).reshape(7, 2)

[0.81898502 0.95347486 1.06104793 0.38488284 0.27980965 0.92361162
 0.91482087]
[1.38180893 0.25133617 1.02875473 1.34339259 1.50608689 1.50831634
 0.13148068]


array([[0.81898502, 1.38180893],
       [0.95347486, 0.25133617],
       [1.06104793, 1.02875473],
       [0.38488284, 1.34339259],
       [0.27980965, 1.50608689],
       [0.92361162, 1.50831634],
       [0.91482087, 0.13148068]])

In [105]:
# ex. 14, Generate a 10x10 matrix. Generate a single random number. Find the number in the matrix closest to it.
vector=np.random.rand(100)
vector10x10= np.random.random((10,10))

x=np.random.rand(1)
y=x[0]
s=vector[0]
for i in np.arange(len(vector)):
    if abs(y-vector[i])<abs(y-s): s=vector[i]
print(s)

0.1450528686232444
