In [11]:
### Tema BasicStatistics

# Exercitiul 1

In [2]:
import numpy as np
import pandas as pd
import scipy
import matplotlib.pyplot as plt
import math as m
import scipy.stats as stats

In [40]:
# 1. Ar fi interesant de facut un experiment cu 5, 10, 30 de observatii. Notati rezultatele.

vector5=np.random.binomial(1,0.5,5)
vector10=np.random.binomial(1,0.5,10)
vector30=np.random.binomial(1,0.5,30)
print("5 aruncari "), print(vector5)
print("10 aruncari "), print(vector10)
print("30 aruncari "), print(vector30)

5 aruncari 
[0 1 0 1 1]
10 aruncari 
[1 1 1 0 1 1 0 1 0 1]
30 aruncari 
[0 1 0 1 1 1 1 1 0 0 0 1 0 0 1 0 1 0 1 0 0 0 1 1 0 1 1 1 1 0]


(None, None)

In [41]:
# 2. Testati rezultatele cu hypothesis testing folosind ca ipoteza nula p=0.5.

heads5 = np.sum(vector5[vector5==1])
print("Test de ipoteza pentru 5 aruncari ")
print(stats.binom_test(x=[5-heads5, heads5], p=0.5, alternative='two-sided'))
print("Test de ipoteza pentru 10 aruncari ")
heads10 = np.sum(vector10[vector10==1])
print(stats.binom_test(x=[10-heads10, heads10], p=0.5, alternative='two-sided'))
print("Test de ipoteza pentru 30 aruncari ")
heads30 = np.sum(vector30[vector30==1])
print(stats.binom_test(x=[30-heads30, heads30], p=0.5, alternative='two-sided'))

Test de ipoteza pentru 5 aruncari 
1.0
Test de ipoteza pentru 10 aruncari 
0.3437499999999999
Test de ipoteza pentru 30 aruncari 
0.8555355519056318


In [42]:
# 3. Ce putem spune despre felul in care evolueaza intervalul de incredere?

n, min_max, mean, var, skew, kurt = stats.describe(vector5)
std=m.sqrt(var)
# We will assume a normal distribution
print('Confidence interval pentur 5 aruncari:', stats.norm.interval(0.95,loc=mean,scale=std/m.sqrt(n)))

n, min_max, mean, var, skew, kurt = stats.describe(vector10)
std=m.sqrt(var)
# We will assume a normal distribution
print('Confidence interval pentru  10 aruncari:', stats.norm.interval(0.95,loc=mean,scale=std/m.sqrt(n)))

n, min_max, mean, var, skew, kurt = stats.describe(vector30)
std=m.sqrt(var)
# We will assume a normal distribution
print('Confidence interval pentru 30 aruncari:', stats.norm.interval(0.95,loc=mean,scale=std/m.sqrt(n)))

print("RASPUNS, deci cu cat numarul de incercari este mai mare, intervalul de confidenta devine mai restrans.")

Confidence interval pentur 5 aruncari: (0.11990883236446898, 1.080091167635531)
Confidence interval pentru  10 aruncari: (0.4006105560485982, 0.9993894439514017)
Confidence interval pentru 30 aruncari: (0.35176009195114655, 0.7149065747155201)
RASPUNS, deci cu cat numarul de incercari este mai mare, intervalul de confidenta devine mai restrans.


In [49]:
# Exercitiul 2

# Verificati daca exista vre-o corelatie intre inaltimea fetelor sau baietilor in raport cu mamele lor. 
# 1. Masurati coeficientul de corelatie dintre aceste variabile 

pearson = pd.read_csv('pearson.csv')
ms = pearson[pearson['gp']=='ms']
md = pearson[pearson['gp']=='md']

print("Coeficientul de corelatie pearson(+eroare) intre inaltimea baietilor in raport cu mamele lor este ")
print(stats.pearsonr(ms['parent'], ms['child']))

print("Coeficientul de corelatie pearson(+eraore) intre inaltimea fetelor in raport cu mamele lor este ")
print(stats.pearsonr(md['parent'], md['child']))


Coeficientul de corelatie pearson(+eroare) intre inaltimea baietilor in raport cu mamele lor este 
(0.48491768425178655, 9.100362271636465e-12)
Coeficientul de corelatie pearson(+eraore) intre inaltimea fetelor in raport cu mamele lor este 
(0.46743677130124, 1.9747722235599194e-11)


In [59]:
# 2. Comentati aceste rezultate in comparatie cu cele obtinute pentru parintii de sex masculin si copii lor

fs = pearson[pearson['gp']=='fs']
fd = pearson[pearson['gp']=='fd']
print("Coeficientul de corelatie pearson(+eroare) intre inaltimea baietilor in raport cu tati lor este ")
print(stats.pearsonr(fs['parent'], fs['child']))
print("Coeficientul de corelatie pearson(+eroare) intre inaltimea fetelor in raport cu tati lor este ")
print(stats.pearsonr(fd['parent'], fd['child']))
print(" ")
print("Cum erorile sant mai mici cu grad de 100, sau 1000,(fata de cele de la copii in relatie cu mamele lor) coeficientul de corelatie intre inaltimea copiilor cu a tatalui este mai semnificativa.")

Coeficientul de corelatie pearson(+eroare) intre inaltimea baietilor in raport cu tati lor este 
(0.520672383091477, 7.95436981660149e-14)
Coeficientul de corelatie pearson(+eroare) intre inaltimea fetelor in raport cu tati lor este 
(0.47205300652210314, 7.905672025208357e-13)
 
Cum erorile sant mai mici cu grad de 100, sau 1000,(fata de cele de la copii in relatie cu mamele lor) coeficientul de corelatie intre inaltimea copiilor cu a tatalui este mai semnificativa
